/* ==========================================================================
   Digital Saathi — web server
   Serves the site, the admin panel (/admin) and a small JSON API for content,
   orders with tracking, contact messages, image uploads and the help chat.
   Data lives in ./data (JSON files) and uploaded images in ./uploads.
   ========================================================================== */

"use strict";

const express = require("express");
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = __dirname;
const DATA_DIR = path.join(ROOT, "data");
const UPLOAD_DIR = path.join(ROOT, "uploads");
const PORT = Number(process.env.PORT) || 8000;
const SESSION_HOURS = 12;

fs.mkdirSync(DATA_DIR, { recursive: true });
fs.mkdirSync(UPLOAD_DIR, { recursive: true });

/* ---------- JSON file storage ---------- */
const file = (name) => path.join(DATA_DIR, name + ".json");
function readJSON(name, fallback) {
  try { return JSON.parse(fs.readFileSync(file(name), "utf8")); } catch (e) { return fallback; }
}
function writeJSON(name, value) {
  const tmp = file(name) + "." + process.pid + ".tmp";
  fs.writeFileSync(tmp, JSON.stringify(value, null, 2));
  fs.renameSync(tmp, file(name));
}

/* ---------- Content (seeded from assets/js/data.js on first run) ---------- */
const CONTENT_KEYS = ["SITE", "OFFER", "CHATBOT", "SERVICES", "COURSES", "TOOLS", "TEACHERS", "SOFTWARE", "BOOST", "TESTIMONIALS", "FAQS"];

function seedContent() {
  const src = fs.readFileSync(path.join(ROOT, "assets/js/data.js"), "utf8");
  const sandbox = { window: {} };
  vm.runInNewContext(src, sandbox, { filename: "data.js" });
  const out = {};
  CONTENT_KEYS.forEach((k) => { if (sandbox.window[k] !== undefined) out[k] = sandbox.window[k]; });
  return JSON.parse(JSON.stringify(out));
}

let content = readJSON("content", null);
if (!content) {
  content = seedContent();
  writeJSON("content", content);
  console.log("Created data/content.json from assets/js/data.js");
} else {
  // Pick up sections added to data.js after the first run
  const seed = seedContent();
  let added = false;
  CONTENT_KEYS.forEach((k) => { if (content[k] === undefined && seed[k] !== undefined) { content[k] = seed[k]; added = true; } });
  if (added) writeJSON("content", content);
}

function contentScript() {
  return "/* Generated by server.js from data/content.json — edit content in the admin panel */\n" +
    CONTENT_KEYS.filter((k) => content[k] !== undefined).map((k) => "window." + k + " = " + JSON.stringify(content[k]) + ";").join("\n") + "\n";
}

const SLUG = /^[a-z0-9][a-z0-9-]{0,63}$/;
function validateContent(key, value) {
  const current = content[key];
  if (Array.isArray(current) !== Array.isArray(value) || typeof value !== "object" || value === null) return "Wrong data type for " + key;
  if (["COURSES", "TOOLS", "TEACHERS"].includes(key)) {
    const ids = new Set();
    for (const item of value) {
      if (!item || typeof item !== "object") return "Every entry must be an object";
      if (!SLUG.test(String(item.id || ""))) return "Invalid id \"" + item.id + "\" — use lowercase letters, numbers and dashes";
      if (ids.has(item.id)) return "Duplicate id \"" + item.id + "\"";
      ids.add(item.id);
      if (!item.title && !item.name) return "Entry \"" + item.id + "\" needs a title";
    }
  }
  if (key === "COURSES") {
    const teachers = new Set(content.TEACHERS.map((t) => t.id));
    const bad = value.find((c) => !teachers.has(c.teacher));
    if (bad) return "Course \"" + bad.id + "\" has unknown teacher \"" + bad.teacher + "\"";
  }
  if (key === "TEACHERS") {
    const ids = new Set(value.map((t) => t.id));
    const orphan = content.COURSES.find((c) => !ids.has(c.teacher));
    if (orphan) return "Teacher \"" + orphan.teacher + "\" is still used by course \"" + orphan.id + "\"";
  }
  if (key === "SERVICES") {
    for (const [k, s] of Object.entries(value)) {
      if (!SLUG.test(k) || s.key !== k) return "Service key \"" + k + "\" must match its key field";
      if (!Array.isArray(s.plans) || !s.plans.length) return "Service \"" + k + "\" needs at least one plan";
    }
  }
  return null;
}

/* ---------- Admin password & sessions ---------- */
function hashPassword(pw, salt) {
  salt = salt || crypto.randomBytes(16).toString("hex");
  return { salt, hash: crypto.scryptSync(pw, salt, 64).toString("hex") };
}
function checkPassword(pw) {
  const a = readJSON("admin", null);
  if (!a) return false;
  const h = Buffer.from(hashPassword(String(pw), a.salt).hash, "hex");
  return crypto.timingSafeEqual(h, Buffer.from(a.hash, "hex"));
}
function setPassword(pw) { writeJSON("admin", hashPassword(pw)); }

// `node server.js --set-password <new password>` resets the admin password
const pwFlag = process.argv.indexOf("--set-password");
if (pwFlag !== -1) {
  const pw = process.argv[pwFlag + 1];
  if (!pw || pw.length < 8) { console.error("Password must be at least 8 characters."); process.exit(1); }
  setPassword(pw);
  console.log("Admin password updated.");
  process.exit(0);
}
if (!readJSON("admin", null)) {
  const initial = process.env.ADMIN_PASSWORD || crypto.randomBytes(6).toString("base64url");
  setPassword(initial);
  console.log("\n  Admin panel password: " + initial + "\n  (change it in Admin → Settings, or run: node server.js --set-password <new>)\n");
}

const sessions = new Map(); // token -> expiry
function parseCookies(req) {
  const out = {};
  (req.headers.cookie || "").split(";").forEach((p) => {
    const i = p.indexOf("=");
    if (i > 0) out[p.slice(0, i).trim()] = decodeURIComponent(p.slice(i + 1).trim());
  });
  return out;
}
function isAdmin(req) {
  const t = parseCookies(req).ds_admin;
  const exp = t && sessions.get(t);
  if (!exp) return false;
  if (exp < Date.now()) { sessions.delete(t); return false; }
  return true;
}
function requireAdmin(req, res, next) {
  if (!isAdmin(req)) return res.status(401).json({ error: "Please log in again." });
  next();
}

/* ---------- Simple per-IP rate limiting ---------- */
const buckets = new Map();
function limit(name, max, windowMs) {
  return (req, res, next) => {
    const key = name + ":" + req.ip;
    const now = Date.now();
    const b = buckets.get(key) || { n: 0, reset: now + windowMs };
    if (now > b.reset) { b.n = 0; b.reset = now + windowMs; }
    b.n++;
    buckets.set(key, b);
    if (b.n > max) return res.status(429).json({ error: "Too many requests — please try again in a few minutes." });
    next();
  };
}
setInterval(() => { const now = Date.now(); buckets.forEach((b, k) => { if (now > b.reset) buckets.delete(k); }); }, 10 * 60 * 1000).unref();

/* ---------- Helpers ---------- */
const str = (v, max) => String(v == null ? "" : v).trim().slice(0, max || 200);
const digits = (v) => String(v || "").replace(/\D/g, "");
const ID_CHARS = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
function newId(prefix) {
  const bytes = crypto.randomBytes(6);
  let s = "";
  for (let i = 0; i < 6; i++) s += ID_CHARS[bytes[i] % ID_CHARS.length];
  return prefix + s;
}

/* ---------- Orders ---------- */
const STAGES = ["received", "confirmed", "in_progress", "review", "delivered", "cancelled"];
const STAGE_NOTES = {
  received: "We've received your order and will confirm it shortly.",
  confirmed: "Payment confirmed. Your order is in the queue.",
  in_progress: "Our team is working on your order.",
  review: "Your work is ready — please review it and share feedback.",
  delivered: "Delivered. Thank you for choosing Digital Saathi!",
  cancelled: "This order was cancelled."
};

// Look up a cart line on the server so prices can't be changed by the browser
function resolveItem(it) {
  const kind = str(it && it.kind, 20), id = str(it && it.id, 120);
  if (kind === "course" || kind === "tool") {
    const src = kind === "course" ? content.COURSES : content.TOOLS;
    const x = src.find((c) => c.id === id);
    return x && { kind, id, title: x.title, price: x.price, oldPrice: x.oldPrice || x.price };
  }
  if (kind === "plan") {
    const [skey, ...rest] = id.split("|");
    const s = content.SERVICES[skey];
    const p = s && s.plans.find((pl) => pl.name === rest.join("|"));
    return p && { kind, id, service: skey, title: s.title + " — " + p.name, unit: p.unit, price: p.price, oldPrice: p.oldPrice || p.price };
  }
  return null;
}

function publicOrder(o) {
  return {
    id: o.id, createdAt: o.createdAt, updatedAt: o.updatedAt, status: o.status, progress: o.progress,
    customer: str(o.customer.name, 60).split(" ")[0],
    items: o.items.map((i) => ({ kind: i.kind, title: i.title, price: i.price, service: i.service })),
    total: o.total, payment: o.payment, assignee: o.assignee || "", deliveryUrl: o.deliveryUrl || "",
    hasService: o.items.some((i) => i.kind === "plan"),
    timeline: o.timeline.map((t) => ({ status: t.status, note: t.note, at: t.at }))
  };
}

/* ---------- App ---------- */
const app = express();
app.disable("x-powered-by");
app.set("trust proxy", "loopback");
app.use((req, res, next) => {
  res.set("X-Content-Type-Options", "nosniff");
  res.set("Referrer-Policy", "strict-origin-when-cross-origin");
  next();
});

// API bodies must be JSON (blocks cross-site form posts)
app.use("/api", (req, res, next) => {
  if (req.method !== "GET" && !req.is("application/json")) return res.status(415).json({ error: "Send JSON" });
  next();
}, express.json({ limit: "8mb" }));

/* Public content */
app.get("/assets/js/data.js", (req, res) => {
  res.type("application/javascript").set("Cache-Control", "no-cache").send(contentScript());
});
app.get("/api/content", (req, res) => res.json(content));

/* Orders: create + track */
app.post("/api/orders", limit("order", 20, 60 * 60 * 1000), (req, res) => {
  const b = req.body || {};
  const name = str(b.name, 80), phone = str(b.phone, 30), email = str(b.email, 120);
  if (!name || digits(phone).length < 7) return res.status(400).json({ error: "Please enter your name and a valid phone number." });
  const items = (Array.isArray(b.items) ? b.items.slice(0, 30) : []).map(resolveItem).filter(Boolean);
  if (!items.length) return res.status(400).json({ error: "Your cart is empty or has items that are no longer available." });
  const orders = readJSON("orders", []);
  let id;
  do { id = newId("DS-"); } while (orders.some((o) => o.id === id));
  const now = new Date().toISOString();
  const order = {
    id, createdAt: now, updatedAt: now, status: "received", progress: 5,
    customer: { name, phone, email }, payment: str(b.payment, 40), brief: str(b.brief, 2000),
    items, total: items.reduce((s, i) => s + Number(i.price || 0), 0),
    assignee: "", deliveryUrl: "", adminNote: "",
    timeline: [{ status: "received", note: STAGE_NOTES.received, at: now }]
  };
  orders.unshift(order);
  writeJSON("orders", orders);
  res.status(201).json({ order: publicOrder(order) });
});

app.post("/api/track", limit("track", 60, 15 * 60 * 1000), (req, res) => {
  const id = str(req.body && req.body.id, 20).toUpperCase().replace(/^(?!DS-)/, "DS-");
  const phone = digits(req.body && req.body.phone);
  const o = readJSON("orders", []).find((x) => x.id === id);
  // Match on the last 7 digits so +977 / 0 prefixes don't matter
  if (!o || phone.length < 7 || digits(o.customer.phone).slice(-7) !== phone.slice(-7)) {
    return res.status(404).json({ error: "We couldn't find an order with that ID and phone number." });
  }
  res.json({ order: publicOrder(o) });
});

/* Contact form / teacher applications */
app.post("/api/messages", limit("msg", 20, 60 * 60 * 1000), (req, res) => {
  const b = req.body || {};
  const fields = {};
  Object.keys(b.fields || {}).slice(0, 20).forEach((k) => { fields[str(k, 40)] = str(b.fields[k], 3000); });
  if (!Object.values(fields).some(Boolean)) return res.status(400).json({ error: "Message is empty." });
  const msgs = readJSON("messages", []);
  msgs.unshift({ id: newId("M-"), type: str(b.type, 120) || "Inquiry", fields, createdAt: new Date().toISOString(), read: false });
  writeJSON("messages", msgs.slice(0, 5000));
  res.status(201).json({ ok: true });
});

/* ---------- Help chat (Claude when ANTHROPIC_API_KEY is set) ---------- */
let claude = null;
if (process.env.ANTHROPIC_API_KEY) {
  const major = Number(process.versions.node.split(".")[0]);
  if (major < 18) {
    console.warn("ANTHROPIC_API_KEY is set but AI chat needs Node 18+ (you have " + process.version + "). Using built-in answers.");
  } else {
    try {
      const mod = require("@anthropic-ai/sdk");
      const Anthropic = mod.default || mod;
      claude = new Anthropic();
      console.log("AI help chat enabled (Claude).");
    } catch (e) {
      console.warn("Could not load @anthropic-ai/sdk — run npm install. Using built-in answers.");
    }
  }
}

function chatSystemPrompt() {
  const c = content;
  const npr = (n) => "Rs. " + Number(n).toLocaleString("en-IN");
  const lines = [];
  lines.push("You are Saathi, the friendly help assistant on the Digital Saathi website (Nepal).");
  lines.push("Digital Saathi sells online courses, editing tools/titles packs, and services: graphic design, video editing and Facebook boost. Prices are in NPR.");
  lines.push("Answer briefly (2-5 short sentences), in the language the visitor uses (English, Nepali or Romanized Nepali). Only use the facts below; if you don't know, suggest WhatsApp " + c.SITE.phone + ".");
  lines.push("To order: add items or a service package to the cart and check out; the visitor gets an order ID and can follow progress on track.html. Payment: eSewa, Khalti, bank/Fonepay QR.");
  lines.push("Never invent prices, discounts or delivery promises that aren't listed. Link pages as plain paths like services.html or course.html?id=<id>.");
  lines.push("\nContact: phone " + c.SITE.phone + ", email " + c.SITE.email + ", " + c.SITE.address + ", hours " + c.SITE.hours + ".");
  lines.push("\nSERVICES:");
  Object.values(c.SERVICES).forEach((s) => {
    lines.push("- " + s.title + " (service.html?id=" + s.key + "): " + s.blurb);
    s.plans.forEach((p) => lines.push("  • " + p.name + ": " + npr(p.price) + " " + p.unit + " — " + p.features.join(", ")));
    s.faqs.forEach((f) => lines.push("  Q: " + f.q + " A: " + f.a));
  });
  lines.push("\nCOURSES:");
  c.COURSES.forEach((x) => lines.push("- " + x.title + " (course.html?id=" + x.id + "): " + npr(x.price) + ", " + x.level + ", " + x.hours + "h. " + (x.summary || "")));
  lines.push("\nEDITING TOOLS:");
  c.TOOLS.forEach((x) => lines.push("- " + x.title + " (product.html?id=" + x.id + "): " + npr(x.price)));
  lines.push("\nFAQ:");
  c.FAQS.forEach((f) => lines.push("Q: " + f.q + " A: " + f.a));
  (c.CHATBOT && c.CHATBOT.answers || []).forEach((a) => lines.push("Q: " + a.keywords + " A: " + a.answer));
  return lines.join("\n");
}

app.get("/api/chat/status", (req, res) => res.json({ ai: Boolean(claude) }));
app.post("/api/chat", limit("chat", 40, 60 * 60 * 1000), async (req, res) => {
  if (!claude) return res.status(503).json({ error: "AI chat is not enabled." });
  const history = (Array.isArray(req.body && req.body.messages) ? req.body.messages : [])
    .slice(-12)
    .map((m) => ({ role: m.role === "assistant" ? "assistant" : "user", content: str(m.content, 1500) }))
    .filter((m) => m.content);
  while (history.length && history[0].role !== "user") history.shift();
  if (!history.length || history[history.length - 1].role !== "user") return res.status(400).json({ error: "Ask a question." });
  try {
    const response = await claude.beta.messages.create({
      model: "claude-opus-5-5",
      max_tokens: 4000,
      betas: ["server-side-fallback-2026-07-01"],
      fallbacks: "default",
      output_config: { effort: "low" },
      system: [{ type: "text", text: chatSystemPrompt(), cache_control: { type: "ephemeral" } }],
      messages: history
    });
    if (response.stop_reason === "refusal") return res.json({ reply: "Sorry, I can't help with that here. For anything else, message us on WhatsApp at " + content.SITE.phone + "." });
    const reply = response.content.filter((b) => b.type === "text").map((b) => b.text).join("").trim();
    res.json({ reply: reply || "Sorry, I didn't catch that. Could you rephrase?" });
  } catch (e) {
    console.error("Chat error:", e.status || "", e.message);
    res.status(502).json({ error: "The assistant is unavailable right now." });
  }
});

/* ---------- Admin API ---------- */
app.post("/api/admin/login", limit("login", 10, 15 * 60 * 1000), (req, res) => {
  if (!checkPassword(req.body && req.body.password)) return res.status(401).json({ error: "Wrong password." });
  const token = crypto.randomBytes(32).toString("hex");
  sessions.set(token, Date.now() + SESSION_HOURS * 3600 * 1000);
  res.cookie("ds_admin", token, { httpOnly: true, sameSite: "strict", secure: req.secure, maxAge: SESSION_HOURS * 3600 * 1000, path: "/" });
  res.json({ ok: true });
});
app.post("/api/admin/logout", (req, res) => {
  sessions.delete(parseCookies(req).ds_admin);
  res.clearCookie("ds_admin", { path: "/" });
  res.json({ ok: true });
});
app.get("/api/admin/me", (req, res) => res.json({ loggedIn: isAdmin(req) }));

app.use("/api/admin", requireAdmin);

app.post("/api/admin/password", (req, res) => {
  const { current, next } = req.body || {};
  if (!checkPassword(current)) return res.status(400).json({ error: "Current password is wrong." });
  if (!next || String(next).length < 8) return res.status(400).json({ error: "New password must be at least 8 characters." });
  setPassword(String(next));
  const keep = parseCookies(req).ds_admin;
  sessions.forEach((_, t) => { if (t !== keep) sessions.delete(t); });
  res.json({ ok: true });
});

app.get("/api/admin/stats", (req, res) => {
  const orders = readJSON("orders", []), msgs = readJSON("messages", []);
  const active = orders.filter((o) => !["delivered", "cancelled"].includes(o.status));
  res.json({
    orders: orders.length, activeOrders: active.length,
    revenue: orders.filter((o) => o.status !== "cancelled" && o.status !== "received").reduce((s, o) => s + o.total, 0),
    unread: msgs.filter((m) => !m.read).length,
    courses: content.COURSES.length, tools: content.TOOLS.length, teachers: content.TEACHERS.length, services: Object.keys(content.SERVICES).length,
    byStatus: STAGES.reduce((acc, s) => { acc[s] = orders.filter((o) => o.status === s).length; return acc; }, {}),
    recentOrders: orders.slice(0, 6), recentMessages: msgs.slice(0, 5)
  });
});

app.put("/api/admin/content/:key", (req, res) => {
  const key = req.params.key;
  if (!CONTENT_KEYS.includes(key)) return res.status(404).json({ error: "Unknown section" });
  const value = req.body && req.body.value;
  const err = validateContent(key, value);
  if (err) return res.status(400).json({ error: err });
  content[key] = value;
  writeJSON("content", content);
  res.json({ ok: true });
});

app.post("/api/admin/content/reset/:key", (req, res) => {
  const key = req.params.key;
  const seed = seedContent();
  if (!CONTENT_KEYS.includes(key) || seed[key] === undefined) return res.status(404).json({ error: "Unknown section" });
  content[key] = seed[key];
  writeJSON("content", content);
  res.json({ ok: true, value: content[key] });
});

app.get("/api/admin/orders", (req, res) => res.json({ orders: readJSON("orders", []), stages: STAGES, notes: STAGE_NOTES }));
app.patch("/api/admin/orders/:id", (req, res) => {
  const orders = readJSON("orders", []);
  const o = orders.find((x) => x.id === req.params.id);
  if (!o) return res.status(404).json({ error: "Order not found" });
  const b = req.body || {};
  const now = new Date().toISOString();
  if (b.status !== undefined) {
    if (!STAGES.includes(b.status)) return res.status(400).json({ error: "Unknown status" });
    const note = str(b.note, 500) || (b.status !== o.status ? STAGE_NOTES[b.status] : "");
    if (b.status !== o.status || note) o.timeline.push({ status: b.status, note, at: now });
    o.status = b.status;
  }
  if (b.progress !== undefined) o.progress = Math.max(0, Math.min(100, Math.round(Number(b.progress) || 0)));
  if (b.assignee !== undefined) o.assignee = str(b.assignee, 80);
  if (b.deliveryUrl !== undefined) {
    const u = str(b.deliveryUrl, 500);
    if (u && !/^https?:\/\//i.test(u)) return res.status(400).json({ error: "Delivery link must start with http:// or https://" });
    o.deliveryUrl = u;
  }
  if (b.adminNote !== undefined) o.adminNote = str(b.adminNote, 2000);
  if (o.status === "delivered") o.progress = 100;
  o.updatedAt = now;
  writeJSON("orders", orders);
  res.json({ order: o });
});
app.delete("/api/admin/orders/:id", (req, res) => {
  writeJSON("orders", readJSON("orders", []).filter((o) => o.id !== req.params.id));
  res.json({ ok: true });
});

app.get("/api/admin/messages", (req, res) => res.json({ messages: readJSON("messages", []) }));
app.patch("/api/admin/messages/:id", (req, res) => {
  const msgs = readJSON("messages", []);
  const m = msgs.find((x) => x.id === req.params.id);
  if (!m) return res.status(404).json({ error: "Message not found" });
  m.read = Boolean(req.body && req.body.read);
  writeJSON("messages", msgs);
  res.json({ ok: true });
});
app.delete("/api/admin/messages/:id", (req, res) => {
  writeJSON("messages", readJSON("messages", []).filter((m) => m.id !== req.params.id));
  res.json({ ok: true });
});

/* Image uploads (sent as a data URL) */
const IMAGE_TYPES = {
  "image/png": { ext: "png", magic: (b) => b.slice(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])) },
  "image/jpeg": { ext: "jpg", magic: (b) => b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff },
  "image/webp": { ext: "webp", magic: (b) => b.slice(0, 4).toString() === "RIFF" && b.slice(8, 12).toString() === "WEBP" },
  "image/gif": { ext: "gif", magic: (b) => b.slice(0, 4).toString() === "GIF8" }
};
app.post("/api/admin/upload", (req, res) => {
  const m = /^data:(image\/[a-z]+);base64,([A-Za-z0-9+/=]+)$/.exec(String(req.body && req.body.dataUrl || ""));
  const type = m && IMAGE_TYPES[m[1]];
  if (!type) return res.status(400).json({ error: "Upload a PNG, JPG, WEBP or GIF image." });
  const buf = Buffer.from(m[2], "base64");
  if (!type.magic(buf)) return res.status(400).json({ error: "That file doesn't look like a valid image." });
  if (buf.length > 5 * 1024 * 1024) return res.status(400).json({ error: "Image must be under 5 MB." });
  const name = Date.now().toString(36) + "-" + crypto.randomBytes(4).toString("hex") + "." + type.ext;
  fs.writeFileSync(path.join(UPLOAD_DIR, name), buf);
  res.status(201).json({ url: "uploads/" + name });
});

app.use("/api", (req, res) => res.status(404).json({ error: "Not found" }));

/* ---------- Static files (only public folders — never data/ or server code) ---------- */
app.use("/assets", express.static(path.join(ROOT, "assets"), { maxAge: "1h" }));
app.use("/uploads", express.static(path.join(UPLOAD_DIR), { maxAge: "7d" }));
app.use("/admin", express.static(path.join(ROOT, "admin"), { index: "index.html" }));
app.get(["/", "/:page"], (req, res, next) => {
  const page = req.params.page || "index.html";
  if (!/^[a-z0-9-]+\.html$/.test(page)) return next();
  const f = path.join(ROOT, page);
  if (!fs.existsSync(f)) return next();
  res.set("Cache-Control", "no-cache").sendFile(f);
});
app.use((req, res) => res.status(404).sendFile(path.join(ROOT, "404.html")));

app.listen(PORT, () => {
  console.log("Digital Saathi running at http://localhost:" + PORT);
  console.log("Admin panel:              http://localhost:" + PORT + "/admin/");
});
